services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: my-redis
    restart: always
    networks:
      - 'redis-net'
    command: ["redis-server", "--appendonly", "yes"]

  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - '1435:1433'